version: '3.4'
services: 
    leap-api:
      restart: always
      build:
        context: "./api/."
        dockerfile: ./Dockerfile
      ports: 
        - "8500:8500"
    leap-webapp:
      restart: always
      build:
        context: "./webapp/."
        dockerfile: ./Dockerfile
      ports:
        - "8502:8502"
      depends_on:
        - leap-api