# Generated by Django 4.1.9 on 2023-06-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_alter_rank_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
