# Generated by Django 4.1.9 on 2023-06-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_alter_rank_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='favourite_categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='student',
            name='favourite_categories',
            field=models.JSONField(default=list),
        ),
    ]
