# Generated by Django 4.1.9 on 2023-06-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0004_remove_student_favourite_categories_delete_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='student',
        ),
        migrations.RemoveField(
            model_name='sectionrank',
            name='ranks',
        ),
        migrations.AddField(
            model_name='student',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ClassRank',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.DeleteModel(
            name='SectionRank',
        ),
    ]
