# Generated by Django 4.1.9 on 2023-06-24 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0005_remove_rank_student_remove_sectionrank_ranks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualpet',
            old_name='rank',
            new_name='pet_rank',
        ),
        migrations.AlterField(
            model_name='virtualpet',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.student'),
        ),
    ]
