# Generated by Django 4.1.9 on 2023-06-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0007_remove_virtualpet_pet_coin_alter_assignment_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualpet',
            name='pet_coin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
