# Generated by Django 4.1.9 on 2023-06-24 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0010_alter_virtualpet_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualpet',
            name='pet_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='virtualpet',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.student'),
        ),
    ]
