# Generated by Django 4.1.9 on 2023-06-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0012_alter_virtualpet_pet_rank_alter_virtualpet_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualpet',
            name='pet_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='virtualpet',
            name='pet_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='virtualpet',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_pets', to='login_register.student'),
        ),
    ]
