# Generated by Django 4.1.9 on 2023-06-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0016_remove_pet_pet_rank_student_pet_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
