# Generated by Django 4.1.9 on 2023-06-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0018_remove_student_pet_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
