# Generated by Django 4.1.9 on 2023-06-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0019_alter_pet_pet_rank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
