# Generated by Django 4.1.9 on 2023-06-25 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0020_delete_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(max_length=100)),
                ('pet_level', models.PositiveIntegerField(default=1)),
                ('pet_progress', models.PositiveIntegerField(default=0)),
                ('pet_coins', models.PositiveIntegerField(default=0)),
                ('pet_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='login_register.student')),
            ],
        ),
    ]
