# Generated by Django 4.1.9 on 2023-06-25 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0022_student_class_rank_student_overall_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='overall_rank',
        ),
    ]
