# Generated by Django 4.1.9 on 2023-06-25 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0023_remove_student_overall_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_rank',
        ),
        migrations.AlterField(
            model_name='pet',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='login_register.student'),
        ),
    ]
