# Generated by Django 4.1.9 on 2023-06-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0024_remove_pet_pet_rank_alter_pet_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pet_rank',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
