# Generated by Django 4.1.9 on 2023-06-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0025_student_pet_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_name',
            field=models.CharField(default="'NA'", max_length=100),
        ),
    ]
