# Generated by Django 4.1.9 on 2023-06-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('option1', models.CharField(default='Default Option 1', max_length=255)),
                ('option2', models.CharField(default='Default Option 2', max_length=255)),
                ('option3', models.CharField(default='Default Option 3', max_length=255)),
                ('option4', models.CharField(default='Default Option 4', max_length=255)),
                ('correct_answer', models.CharField(default='Nothing', max_length=255)),
            ],
        ),
    ]
