# Generated by Django 4.1.9 on 2023-06-07 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_marks', models.FloatField(default=0)),
                ('average_attendance', models.FloatField(default=0)),
                ('average_assignment_percent', models.FloatField(default=0)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('favourite_categories', models.ManyToManyField(related_name='students', to='login_register.category')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(max_length=100)),
                ('pet_level', models.PositiveIntegerField(default=1)),
                ('pet_level_progress', models.PositiveIntegerField(default=0)),
                ('pet_coin', models.PositiveIntegerField(default=200)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_pet', to='login_register.student')),
            ],
        ),
        migrations.CreateModel(
            name='SectionRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('ranks', models.ManyToManyField(to='login_register.rank')),
            ],
        ),
        migrations.AddField(
            model_name='rank',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.student'),
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths', models.PositiveIntegerField()),
                ('hindi', models.PositiveIntegerField()),
                ('english', models.PositiveIntegerField()),
                ('science', models.PositiveIntegerField()),
                ('social_science', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('average_marks', models.FloatField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.student')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('ranks', models.ManyToManyField(to='login_register.rank')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths_attendance', models.PositiveIntegerField()),
                ('hindi_attendance', models.PositiveIntegerField()),
                ('english_attendance', models.PositiveIntegerField()),
                ('science_attendance', models.PositiveIntegerField()),
                ('social_science_attendance', models.PositiveIntegerField()),
                ('average_attendance', models.FloatField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.student')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_assignments', models.PositiveIntegerField(default=0)),
                ('total_assignments', models.PositiveIntegerField(default=0)),
                ('assignment_percentage', models.FloatField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.student')),
            ],
        ),
    ]
